package middleware

import (
	"net/http"
	"time"

	"github.com/go-chi/chi/v5/middleware"
	"github.com/rs/zerolog"
)

// StructuredLogger creates a context-aware zerolog logger per request
// and records request execution duration, status code, and bytes written.
func StructuredLogger(logger zerolog.Logger) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			start := time.Now()

			// Extract request ID generated by chi's middleware.RequestID.
			reqID := middleware.GetReqID(r.Context())

			// Echo it so clients can correlate their request with our logs.
			// chi's RequestID only puts it in the context, not the response.
			if reqID != "" {
				w.Header().Set(middleware.RequestIDHeader, reqID)
			}

			// Create a contextual logger for this request.
			log := logger.With().
				Str("req_id", reqID).
				Str("method", r.Method).
				Str("path", r.URL.Path).
				Logger()

			// Inject the logger into the request context.
			ctx := log.WithContext(r.Context())

			// Wrap the ResponseWriter to capture status and bytes written.
			ww := middleware.NewWrapResponseWriter(w, r.ProtoMajor)

			// Pass the request to the next handler.
			next.ServeHTTP(ww, r.WithContext(ctx))

			// Log request completion.
			log.Info().
				Int("status", ww.Status()).
				Int("bytes", ww.BytesWritten()).
				Dur("latency", time.Since(start)).
				Msg("handled request")
		})
	}
}
